const archetype = [
    "Blue-Eyes",
    "Elemental HERO",
    "Dark Magician",
    "Burning Abyss",
    "Kuriboh",
    "Red-Eyes",
    "Harpie",
    "Noble Knight",
    "Gouki",
    "Salamangreat",
    "Sky Striker",
    "Madolche",
    "Crystal Beast",
    "Six Samurai",
    "Infernity",
    "Mermail",
    "Yubel",
    "Frog",
    "Gusto",
    "Kozmo",
    "Lunalight",
    "Phantom Knights",
    "Shaddoll",
    "Zoodiac",
    "Dinomist",
    "Predaplant",
    "Trickstar",
    "Altergeist",
    "Toon",
    "Witchcrafter",
    "Mekk-Knight",
    "D/D/D",
    "F.A.",
    "Frightfur",
    "Gagaga",
    "Gimmick Puppet",
    "Ojama",
    "Performapal",
]

export default archetype;